version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: UPI.2026
      MYSQL_DATABASE: wordpress
    networks:
      - wp_network
    volumes:
      - wordpress-pipeline_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    restart: always
    ports:
      - "8086:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: UPI.2026
    networks:
      - wp_network
    volumes:
      - wordpress-pipeline_wp_data:/var/www/html

networks:
  wp_network:

volumes:
  wordpress-pipeline_db_data:
  wordpress-pipeline_wp_data:
